import React, { useState, createContext, useEffect } from 'react'
import {createRoot} from 'react-dom/client'
import './style.css'
import App from './App'
import { FluentProvider, webDarkTheme, webLightTheme } from '@fluentui/react-components'

export const ThemeContext = createContext();

const ThemeProvider = ({ children }) => {
  const [isDark, setIsDark] = useState(null);
  const [loading, setLoading] = useState(true);
  // Load saved theme from Go backend on mount
  useEffect(() => {
    const loadTheme = async () => {
      try {
        // Call Go method (generated by Wails)
        const savedTheme = await window.go.main.App.GetTheme();
        const dark = savedTheme === 'dark';
        setIsDark(dark);
        // Sync body class
        document.body.classList.toggle('dark-theme', dark);
      } catch (error) {
        console.error('Failed to load theme:', error);
        // Default to light theme
        setIsDark(false);
      } finally {
        setLoading(false);
      }
    };
    loadTheme();
  }, []);

  const toggleTheme = async () => {
    if (isDark === null) return; // still loading
    const newIsDark = !isDark;
    const newTheme = newIsDark ? 'dark' : 'light';
    try {
      // Save to backend
      await window.go.main.App.SetTheme(newTheme);
      // Update state
      setIsDark(newIsDark);
      // Update body class for custom CSS
      document.body.classList.toggle('dark-theme', newIsDark);
    } catch (error) {
      console.error('Failed to save theme:', error);
    }
  };

  if (loading) {
    // Optional: render a minimal placeholder while loading
    return <div style={{ visibility: 'hidden' }}>Loading...</div>;
  }

  const currentTheme = isDark ? webDarkTheme : webLightTheme;

  return (
    <ThemeContext.Provider value={{ isDark, toggleTheme }}>
      <FluentProvider theme={currentTheme}>
        {children}
      </FluentProvider>
    </ThemeContext.Provider>
  );
};

const container = document.getElementById('root')
const root = createRoot(container)

root.render(
  <React.StrictMode>
    <ThemeProvider>
      <App />
    </ThemeProvider>
  </React.StrictMode>
);
